version: '3.8'

services:
  backend:
    build: ./djangobackend  # Path to the Django backend Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname  # Example of environment variable
      # Add other environment variables here if necessary

  frontend:
    build: ./reactfrontend  # Path to the React frontend Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
