version: "3.9"

services:
  backend:
    build: ./djangobackend
    ports:
      - "8000:8000"
    volumes:
      - ./djangobackend:/app
    environment:
      - DEBUG=True
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app_network

  frontend:
    build: ./reactfrontend
    ports:
      - "80:80"  
    volumes:
      - ./reactfrontend:/app
      - /app/node_modules  
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
